# Generated by Django 5.2.10 on 2026-01-16 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_public', models.BooleanField(default=False, help_text='هل يمكن للمستخدمين العاديين رؤية هذا الإعداد', verbose_name='عام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد نظام',
                'verbose_name_plural': 'إعدادات النظام',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('export', 'تصدير'), ('import', 'استيراد'), ('promote', 'ترقية')], max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='تمثيل الكائن')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='audit_logs_user_id_d685f3_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
