# Generated by Django 5.2.10 on 2026-01-16 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, unique=True, verbose_name='اسم المستوى')),
                ('level_number', models.PositiveIntegerField(help_text='رقم ترتيبي للمستوى (1, 2, 3, 4) يستخدم في الترقية الجماعية', unique=True, verbose_name='رقم المستوى')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المستوى')),
            ],
            options={
                'verbose_name': 'مستوى',
                'verbose_name_plural': 'المستويات',
                'db_table': 'levels',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=100, unique=True, verbose_name='اسم التخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'db_table': 'majors',
                'ordering': ['major_name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100, unique=True, verbose_name='اسم الصلاحية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصلاحية')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Admin', 'مدير النظام'), ('Instructor', 'مدرس'), ('Student', 'طالب')], max_length=50, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفصل الدراسي')),
                ('academic_year', models.CharField(help_text='مثال: 2025/2026', max_length=20, verbose_name='العام الدراسي')),
                ('semester_number', models.PositiveIntegerField(help_text='1 للفصل الأول، 2 للفصل الثاني', verbose_name='رقم الفصل')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, help_text='يحدد ما إذا كان هذا هو الفصل الدراسي النشط حالياً', verbose_name='الفصل الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'db_table': 'semesters',
                'ordering': ['-academic_year', '-semester_number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('academic_id', models.CharField(help_text='الرقم الأكاديمي للطالب أو الرقم الوظيفي للموظف', max_length=50, unique=True, verbose_name='الرقم الأكاديمي/الوظيفي')),
                ('id_card_number', models.CharField(help_text='يستخدم للتحقق من الهوية عند التفعيل', max_length=50, unique=True, verbose_name='رقم البطاقة الشخصية')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, help_text='يتم تعيينه عند التفعيل', max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('account_status', models.CharField(choices=[('inactive', 'غير مفعّل'), ('active', 'مفعّل'), ('suspended', 'موقوف')], default='inactive', max_length=20, verbose_name='حالة الحساب')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='صورة الملف الشخصي')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('level', models.ForeignKey(blank=True, help_text='للطلاب فقط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.level', verbose_name='المستوى')),
                ('major', models.ForeignKey(blank=True, help_text='للطلاب فقط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.major', verbose_name='التخصص')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='التوكن')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توكن إعادة تعيين',
                'verbose_name_plural': 'توكنات إعادة التعيين',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission', verbose_name='الصلاحية')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية الدور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('upload', 'رفع ملف'), ('download', 'تحميل ملف'), ('view', 'عرض محتوى'), ('ai_summary', 'طلب تلخيص AI'), ('ai_questions', 'طلب أسئلة AI'), ('profile_update', 'تحديث الملف الشخصي'), ('password_change', 'تغيير كلمة المرور')], max_length=50, verbose_name='نوع النشاط')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف النشاط')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
                ('activity_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت النشاط')),
                ('file_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الملف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط مستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'db_table': 'user_activity',
                'ordering': ['-activity_time'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='رمز التحقق')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني المستهدف')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز تحقق',
                'verbose_name_plural': 'رموز التحقق',
                'db_table': 'verification_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['academic_id'], name='users_academi_6f9fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='users_account_33da0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_f188ea_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_time'], name='user_activi_activit_a6d0d4_idx'),
        ),
    ]
