# Generated by Django 5.2.10 on 2026-01-16 08:31

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='اسم المقرر')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='رمز المقرر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المقرر')),
                ('credit_hours', models.PositiveIntegerField(default=3, verbose_name='الساعات المعتمدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='accounts.level', verbose_name='المستوى')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='accounts.semester', verbose_name='الفصل الدراسي')),
            ],
            options={
                'verbose_name': 'مقرر',
                'verbose_name_plural': 'المقررات',
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_majors', to='courses.course', verbose_name='المقرر')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_courses', to='accounts.major', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'ربط مقرر بتخصص',
                'verbose_name_plural': 'ربط المقررات بالتخصصات',
                'db_table': 'course_majors',
            },
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('is_primary', models.BooleanField(default=True, help_text='يحدد ما إذا كان هذا المدرس هو المدرس الرئيسي للمقرر', verbose_name='المدرس الرئيسي')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to='courses.course', verbose_name='المقرر')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to=settings.AUTH_USER_MODEL, verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'تعيين مدرس',
                'verbose_name_plural': 'تعيينات المدرسين',
                'db_table': 'instructor_courses',
            },
        ),
        migrations.CreateModel(
            name='LectureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
                ('content_type', models.CharField(choices=[('local_file', 'ملف محلي'), ('external_link', 'رابط خارجي')], default='local_file', max_length=20, verbose_name='نوع المحتوى')),
                ('local_file', models.FileField(blank=True, null=True, upload_to=courses.models.lecture_file_path, verbose_name='الملف المحلي')),
                ('external_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='الرابط الخارجي')),
                ('file_type', models.CharField(choices=[('Lecture', 'محاضرة'), ('Summary', 'ملخص'), ('Exam', 'اختبار'), ('Assignment', 'واجب'), ('Reference', 'مرجع'), ('Other', 'أخرى')], default='Lecture', max_length=50, verbose_name='تصنيف الملف')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True, verbose_name='امتداد الملف')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع MIME')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_visible', models.BooleanField(default=True, help_text='للتحكم في ظهور الملف للطلاب', verbose_name='مرئي للطلاب')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete - الملف لا يظهر لكنه موجود في قاعدة البيانات', verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course', verbose_name='المقرر')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='رافع الملف')),
            ],
            options={
                'verbose_name': 'ملف محاضرة',
                'verbose_name_plural': 'ملفات المحاضرات',
                'db_table': 'lectures_files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='courses_course__5da9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'semester'], name='courses_level_i_142f5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemajor',
            unique_together={('course', 'major')},
        ),
        migrations.AlterUniqueTogether(
            name='instructorcourse',
            unique_together={('instructor', 'course')},
        ),
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['course', 'file_type'], name='lectures_fi_course__02e733_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['upload_date'], name='lectures_fi_upload__6e2bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturefile',
            index=models.Index(fields=['is_visible', 'is_deleted'], name='lectures_fi_is_visi_d3378e_idx'),
        ),
    ]
