# Generated by Django 5.2.10 on 2026-01-16 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('is_helpful', models.BooleanField(blank=True, help_text='تقييم المستخدم لجودة الإجابة', null=True, verbose_name='مفيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ السؤال')),
                ('response_time', models.FloatField(default=0, verbose_name='وقت الاستجابة (ثانية)')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to='courses.lecturefile', verbose_name='الملف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محادثة AI',
                'verbose_name_plural': 'محادثات AI',
                'db_table': 'ai_chats',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file', 'user'], name='ai_chats_file_id_2efcb8_idx'), models.Index(fields=['created_at'], name='ai_chats_created_567726_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_json', models.JSONField(help_text='الأسئلة والأجوبة بصيغة JSON', verbose_name='الأسئلة والأجوبة')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة')),
                ('question_type', models.CharField(default='mixed', help_text='multiple_choice, true_false, short_answer, mixed', max_length=50, verbose_name='نوع الأسئلة')),
                ('difficulty_level', models.CharField(default='medium', help_text='easy, medium, hard', max_length=20, verbose_name='مستوى الصعوبة')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('generation_time', models.FloatField(default=0, verbose_name='وقت التوليد (ثانية)')),
                ('model_used', models.CharField(default='gemini-pro', max_length=100, verbose_name='النموذج المستخدم')),
                ('is_cached', models.BooleanField(default=True, verbose_name='مخزن مؤقتاً')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='courses.lecturefile', verbose_name='الملف')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_questions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الطالب')),
            ],
            options={
                'verbose_name': 'أسئلة AI',
                'verbose_name_plural': 'أسئلة AI',
                'db_table': 'ai_questions',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['file'], name='ai_question_file_id_4cdd9e_idx'), models.Index(fields=['generated_at'], name='ai_question_generat_cc8c77_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='الملخص بصيغة Markdown', verbose_name='نص الملخص')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='لغة الملخص')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='عدد الكلمات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('generation_time', models.FloatField(default=0, verbose_name='وقت التوليد (ثانية)')),
                ('model_used', models.CharField(default='gemini-pro', max_length=100, verbose_name='النموذج المستخدم')),
                ('is_cached', models.BooleanField(default=True, help_text='يمكن إعادة استخدامه للمستخدمين الآخرين', verbose_name='مخزن مؤقتاً')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='courses.lecturefile', verbose_name='الملف')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_summaries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الطالب')),
            ],
            options={
                'verbose_name': 'ملخص AI',
                'verbose_name_plural': 'ملخصات AI',
                'db_table': 'ai_summaries',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['file'], name='ai_summarie_file_id_90e7b0_idx'), models.Index(fields=['generated_at'], name='ai_summarie_generat_366852_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('summary', 'تلخيص'), ('questions', 'توليد أسئلة'), ('chat', 'محادثة')], max_length=20, verbose_name='نوع الطلب')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='التوكنات المستخدمة')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('was_cached', models.BooleanField(default=False, verbose_name='من الذاكرة المؤقتة')),
                ('success', models.BooleanField(default=True, verbose_name='ناجح')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='courses.lecturefile', verbose_name='الملف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل استخدام AI',
                'verbose_name_plural': 'سجلات استخدام AI',
                'db_table': 'ai_usage_logs',
                'ordering': ['-request_time'],
                'indexes': [models.Index(fields=['user', 'request_time'], name='ai_usage_lo_user_id_dee198_idx'), models.Index(fields=['request_type'], name='ai_usage_lo_request_e64f26_idx')],
            },
        ),
    ]
